---

- name: Ensure Service is Started and Enabled
  service: name=mysql state=started enabled=yes
  sudo: yes
  
- name: Modify configuration file to listen on all interfaces
  ini_file: dest=/etc/my.cnf.d/server.cnf
            section=mysqld
            option=bind-address
            value=0.0.0.0
            backup=yes

- name: Modify configuration file to setup server ID
  ini_file: dest=/etc/my.cnf.d/server.cnf
            section=mysqld
            option=server-id
            value=1
#            value={{ hostvars[groups['database']][0] }}

- name: Modify configuration file to setup bin.log
  ini_file: dest=/etc/my.cnf.d/server.cnf
            section=mysqld
            option=log_bin
            value=/tmp/mysql-bin.log

                                        
- name: Modify configuration file to setup binlog_do_db
  ini_file: dest=/etc/my.cnf.d/server.cnf
            section=mysqld
            option=binlog_do_db
            value={{ replic_db }}

- name: Restart mysql service 
  service: name=mysql state=restarted enabled=yes
  sudo: yes

- name: Create replication account 
  mysql_user: name={{ replic_user }}
              host=%
              password={{ replic_userpassword }}
              priv="*.*:REPLICATION SLAVE"
              state=present

- name: Reset master binlog
  command: mysql -u root -e "RESET MASTER"


